### PR TITLE
Adds Gatsby version 3 to package.json

### PR DESCRIPTION
**Pull request by ghost**
Hello!
As far as my (limited) testing goes, this plugin works with Gatsby v3. 
I've added it as an option so npm doesn't throw a warning that `Plugin gatsby-plugin-glslify is not compatible with your gatsby version 3.1.1 - It requires gatsby@^2.0.0`

Thanks

### CODE REVIEW

**Comment by mfanuzzi** [comment]
+1, I'm using this in production right now on Gatsby 3 and it works just fine.

**Comment by ghost** [comment]
@onnovisser Any updates ?

**Comment by onnovisser** [comment]
Merged, thanks!

**Comment by onnovisser** [comment]
Released as 1.0.1

**Comment by ghost** [comment]
Fantastic, thanks

**Pull request merged**
